name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test
    - name: Perform code coverage
      run: cd build && ctest -T Test -T Coverage > coverage.txt
    - name: Upload coverage result for job 1
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: ./build/coverage.txt

  build-ubuntu-20-04:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test

  build-ubuntu-23-04:

    runs-on: ubuntu-latest
    container: ubuntu:23.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt-get update && apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test

  build-ubuntu-23-10:

    runs-on: ubuntu-latest
    container: ubuntu:23.10

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt-get update && apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test
