name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-ubuntu-22-04:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev gcovr
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src -DUSE_GCOV=1
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test
    - name: Perform code coverage
      run: |
        cd build
        gcovr -r ../ . --xml-pretty -e ".*\.h" > coverage.xml
        gcovr -r ../ . --html -e ".*\.h" > report.html
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./build/report.html
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/coverage.xml


  build-ubuntu-20-04:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src -DUSE_GCOV=1
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test

  build-ubuntu-23-04:

    runs-on: ubuntu-latest
    container: ubuntu:23.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt-get update && apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src -DUSE_GCOV=1
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test

  build-ubuntu-23-10:

    runs-on: ubuntu-latest
    container: ubuntu:23.10

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: apt-get update && apt-get install -y build-essential cmake libboost-all-dev pkg-config libeigen3-dev libtclap-dev
    - name: Configure CMake
      run: mkdir build && cd build && cmake ../src -DUSE_GCOV=1
    - name: Build
      run: cd build && make -j
    - name: Perform unit tests
      run: cd build && make test
